# Generated by Django 3.0.2 on 2020-02-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classblog',
            old_name='upload_at',
            new_name='updated_at',
        ),
    ]
